def main():
    file = open("index.html","w")
    file.write("<!DOCTYPE html>\n")
    file.write("<html>\n")
    file.write("\t<head>\n")
    file.write("\t\t<meta charset=\"utf-8\"/>\n")
    file.write("\t\t<title>Resaltador de Sintaxix</title>\n")
    file.write("\t\t<link rel=\"stylesheet\" href=\"styles.css\">\n")
    file.write("\t</head>\n")
    file.write("\t<body>\n")

    file.write("\t\t<span class=\"reservado\">" + "Palabra Reservada: int, float, for" + "</span>\n")
    file.write("\t\t<br>\n")
    file.write("\t\t<span class=\"operador\">" + "Operador: +, -, =, ;" + "</span>\n")
    file.write("\t\t<br>\n")
    file.write("\t\t<span class=\"literal\">" + "Literal: 4, 6.4, -31.1" + "</span>\n")
    file.write("\t\t<br>\n")
    file.write("\t\t<span class=\"variable\">" + "Variable: hola1, _f4ws, i" + "</span>\n")
    file.write("\t\t<br>\n")
    file.write("\t\t<span class=\"char\">" + "Char: 'a', '5', 'V'" + "</span>\n")
    file.write("\t\t<br>\n")
    file.write("\t\t<span class=\"string\">" + "String: \"Hola\",\"String\"" + "</span>\n")
    file.write("\t\t<br>\n")
    file.write("\t\t<span class=\"comentario\">" + "Comentario: // Esto es un comentario" + "</span>\n")
    file.write("\t\t<br>\n")
    file.write("\t\t<span class=\"error\">" + "1a2svb4v" + "</span>\n")
    file.write("\t\t<br>\n")

    file.write("\t</body>\n")
    file.write("</html>")

main()